# @package _global_
name: biophysical/periodic

defaults:
  - /base
  - _self_

model:
  _target_: src.models.BiophysicalOscillator

simulate:
  _target_: src.simulate.cartesian
  T: 5000
  dt: 1
  v_init: -55.0
  a_init: 0.4

measure:
  _target_: src.analyses.periodic.measure
  widths: [50, 100, 150]
  strengths_range: [-0.08, 0.08, 0.01]
  periods_range: [0.75, 1.25, 0.05]
  pulse_count: 10
  init_every: 0.1

plot:
  _target_: src.analyses.periodic.plot
  waveform_every: [0.02, 0.1]
  slice_every: [0.01, 0.05]
  phase_kws:
    xlim: [-80, 0]
    xref: [-50]
    ylim: [0, 1]

compute:
  cpu: 16
  mem: 16
