# @package _global_
name: simplified/pulse_variants

hydra:
  sweeper:
    params:
      model.k_adaptation_active_pos: 0.5
      model.k_adaptation_active_neg: 1.5
      model.k_adaptation_quiet_pos: 1.5
      model.k_adaptation_quiet_neg: 0.5

defaults:
  - /simplified/pulse_variants_0
  - _self_
